version: '3'
services:
  figure-api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - figure-db
    links:
      - figure-db

  figure-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret